name: E2E

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-build
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Build
              run: yarn build:e2e

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

    test:
        needs: build

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        concurrency:
            group: ${{ github.head_ref }}-e2e-settings-routing
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (Yarn)
              run: yarn install --ignore-engines --frozen-lockfile

            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: ${{ github.workspace }}/build

            - name: Test
              run: xvfb-run --server-args="-screen 0 1920x1080x16" yarn test:e2e

            - name: Upload Screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}-screenshots
                  path: ${{ github.workspace }}/screenshots/**/*
